### ISSUE TITLE
Wordpress multisite

### ISSUE THREAD

**Issue by Lunteer** [cloudflare/templates#51]
This is more of a general question, rather than a particular issue with code.

Does Cloudflare worker work with WordPress Multisite? Particularly when you have different domains on one install.

Do you need to setup different Cloudflare accounts for each domain?

Thanks!!

**Comment by lauragift21** [comment]
Hello @Lunteer! Did you mean can you use the same Cloudflare account to deploy multiple WordPress sites [like this example](https://developers.cloudflare.com/pages/how-to/deploy-a-wordpress-site/)? Then your answer is yes. 

It looks like this issue is stale, but feel free to reopen it in the[workers-sdk repo](https://github.com/cloudflare/workers-sdk/tree/main/templates) where the templates now live. I'll close this now.
